### PR TITLE
ENH: Use YAML for easier writing

### PR DESCRIPTION
**Pull request by effigies**
YAML is a superset of JSON, and much easier to write.

### CODE REVIEW

**Review by oz123 — CHANGES_REQUESTED** [review]
I appreciate this idea. I believe you are correct about YAML being easier than JSON. However, I'd like to have this as a configurable option. So one can choose whether the application accepts YAML or JSON.

**Comment by effigies** [comment]
The main point of this was just that all valid JSON is valid YAML, so there's no loss in functionality, unless strict JSON validation is important?

**Comment by oz123** [comment]
OK. I understand. I can still do:

 > yaml.safe_load('{"foo": "bar"}').

**Review by oz123 — APPROVED** [review]

**Comment by oz123** [comment]
@effigies I am working on making this little application more reusable. See recent changes. Ideas welcome.

**Pull request merged**
